name: 'Export Version'
description: 'Export Gradle Version and Docker Tag'
outputs:
  app-version:
    description: "Application version"
    value: ${{ steps.app-version.outputs.app-version }}
  docker-tag:
    description: "Docker tag"
    value: ${{ steps.docker-tag.outputs.docker-tag }}
runs:
  using: "composite"
  steps:
    - name: get app version
      id: app-version
      shell: bash
      run: |
        APP_VERSION=`grep -oP 'version = [^"]*"\K[^"]*' build.gradle*`
        echo "::set-ouput name=app-version::$(echo $APP_VERSION)"
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

    - name: get docker tag
      id: docker-tag
      shell: bash
      run: |
        DOCKER_TAG=${GITHUB_REF##*/}-$APP_VERSION-${GITHUB_SHA::8}
        echo "::set-ouput name=docker-tag::$(echo $DOCKER_TAG)"
        echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV


